name: "Validate CODEOWNERS"

on:
  push:
    paths:
      - .github/CODEOWNERS
      - .github/workflows/codeowners-validator.yml
  pull_request:
    paths:
      - .github/CODEOWNERS
      - .github/workflows/codeowners-validator.yml
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Validate CODEOWNERS
        uses: ryan-flan/codeowners-validation@v0.4.10
        with:
          checks: "all"
          path: ".github/CODEOWNERS"
